### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by moesaif**
# as Redis-Go v7 uses https://github.com/golang/go/wiki/Modules do this command first it sometimes needs to be initated 
$ go mod init github.com/go-redis/redis/v7

### CODE REVIEW

**Comment by adonese** [comment]
Does this prevent you from building noebs with modules support? I believe i updated it, but i'm gonna check it today

**Comment by adonese** [comment]
`go mod init github.com/go-redis/redis/v7`
this is valid for go-redis, but for noebs we use
`go mod init github.com/adonese/noebs`

In essence, in go we used to have gopath, where all of our packages are stored there. And then they added support for modules, essentially that allows us to have our go projects in arbitrary system directory. To make a new go mod project, you do this:
- `go mod init my-project-name`

when you want to import a new package to your project, you simply use: go get path/to/the/new/package

I hope that clarifies it

**Comment by moesaif** [comment]
You didn't get me , i had the package already but it has to be initiated specifically that was error i faced

**Comment by adonese** [comment]
> 
> 
> You didn't get me , i had the package already but it has to be initiated specifically that was error i faced

Sorry for that, could you please describe the error you faced? Is it regarding noebs or redis package? 

What happened, and how did you fix it?

**Pull request closed without merging**
